//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManagerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.WebApp.Resources.ManagerResource", typeof(ManagerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BT_ALLOW {
            get {
                return ResourceManager.GetString("BT_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string BT_CANCEL {
            get {
                return ResourceManager.GetString("BT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn sản phẩm.
        /// </summary>
        public static string BT_CHOOSE_PRODUCT {
            get {
                return ResourceManager.GetString("BT_CHOOSE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        public static string BT_CLEAR {
            get {
                return ResourceManager.GetString("BT_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file CSV.
        /// </summary>
        public static string BT_OUTPUT_CSV {
            get {
                return ResourceManager.GetString("BT_OUTPUT_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        public static string BT_RESET {
            get {
                return ResourceManager.GetString("BT_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang bận, vui lòng thử lại sau.
        /// </summary>
        public static string COMMON_ERROR_EXTERNALSERVICE_TIMEOUT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_EXTERNALSERVICE_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa ?.
        /// </summary>
        public static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và xác nhận mật khẩu không khớp.
        /// </summary>
        public static string ERROR_CONFRIM_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_CONFRIM_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu phải nhỏ hơn thời gian kết thúc.
        /// </summary>
        public static string ERROR_DATE_RANGE_IN_PAST {
            get {
                return ResourceManager.GetString("ERROR_DATE_RANGE_IN_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị đã tồn tại, vui lòng kiểm tra lại !.
        /// </summary>
        public static string ERROR_ENUMVALUE_EXISTED {
            get {
                return ResourceManager.GetString("ERROR_ENUMVALUE_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng trong kho không đủ {0} để xuất. Vui lòng kiểm tra lại.
        /// </summary>
        public static string ERROR_GOODS_ISSUE_NOT_ENOUGH_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_GOODS_ISSUE_NOT_ENOUGH_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng !.
        /// </summary>
        public static string ERROR_INVALID_LOGIN {
            get {
                return ResourceManager.GetString("ERROR_INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được để trống.
        /// </summary>
        public static string ERROR_NOT_NULL_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_NOT_NULL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn sản phẩm.
        /// </summary>
        public static string ERROR_NOT_SELECT_ITEM {
            get {
                return ResourceManager.GetString("ERROR_NOT_SELECT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thành viên.
        /// </summary>
        public static string ERROR_NOT_SELECT_MEMBER {
            get {
                return ResourceManager.GetString("ERROR_NOT_SELECT_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập giá trị tối thiểu phải lớn hơn 0.
        /// </summary>
        public static string ERROR_NUMBER_MIN_0 {
            get {
                return ResourceManager.GetString("ERROR_NUMBER_MIN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy trang.
        /// </summary>
        public static string ERROR_PAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_PAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền sử dụng chức năng này !!!.
        /// </summary>
        public static string ERROR_PERMISSION_DENNIED {
            get {
                return ResourceManager.GetString("ERROR_PERMISSION_DENNIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đúng định dạng.
        /// </summary>
        public static string ERROR_PHONE_INVALID {
            get {
                return ResourceManager.GetString("ERROR_PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm [{0}]. Vui lòng kiểm tra lại !.
        /// </summary>
        public static string ERROR_PRODUCT_ITEM_CODE_NOTFOUND_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_PRODUCT_ITEM_CODE_NOTFOUND_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm. Vui lòng kiểm tra lại !.
        /// </summary>
        public static string ERROR_PRODUCT_ITEM_NOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_PRODUCT_ITEM_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhập vào phải lớn hơn 0.
        /// </summary>
        public static string ERROR_QTY_MUST_LARGE_THAN_0 {
            get {
                return ResourceManager.GetString("ERROR_QTY_MUST_LARGE_THAN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian định kỳ phải nằm trong khoảng từ 1 đến 24 tháng.
        /// </summary>
        public static string ERROR_SYSTEM_PERIOD_MIN_0_MAX_24 {
            get {
                return ResourceManager.GetString("ERROR_SYSTEM_PERIOD_MIN_0_MAX_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm này đã kiểm kê xong !.
        /// </summary>
        public static string ERROR_THIS_ITEM_DONT_NEED_REFLECT {
            get {
                return ResourceManager.GetString("ERROR_THIS_ITEM_DONT_NEED_REFLECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại.
        /// </summary>
        public static string ERROR_USERNAME_EXISTED {
            get {
                return ResourceManager.GetString("ERROR_USERNAME_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khóa.
        /// </summary>
        public static string LB_ACCOUNT_LOCKED {
            get {
                return ResourceManager.GetString("LB_ACCOUNT_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đang hoạt động.
        /// </summary>
        public static string LB_ACCOUNT_NOT_LOCKED {
            get {
                return ResourceManager.GetString("LB_ACCOUNT_NOT_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã bị khóa !.
        /// </summary>
        public static string LB_ACCOUNT_WAS_LOCKED {
            get {
                return ResourceManager.GetString("LB_ACCOUNT_WAS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động.
        /// </summary>
        public static string LB_ACTION {
            get {
                return ResourceManager.GetString("LB_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kích hoạt.
        /// </summary>
        public static string LB_ACTIVATED {
            get {
                return ResourceManager.GetString("LB_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string LB_ACTIVE {
            get {
                return ResourceManager.GetString("LB_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bài viết.
        /// </summary>
        public static string LB_ADD_NEW_POST {
            get {
                return ResourceManager.GetString("LB_ADD_NEW_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string LB_ADDNEW {
            get {
                return ResourceManager.GetString("LB_ADDNEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string LB_ADDRESS {
            get {
                return ResourceManager.GetString("LB_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string LB_ALL {
            get {
                return ResourceManager.GetString("LB_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cho phép hiển thị trên bộ lọc.
        /// </summary>
        public static string LB_ALLOW_SHOW_FILTER {
            get {
                return ResourceManager.GetString("LB_ALLOW_SHOW_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại.
        /// </summary>
        public static string LB_ASSIGN_CATEGORY {
            get {
                return ResourceManager.GetString("LB_ASSIGN_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm quản trị viên.
        /// </summary>
        public static string LB_ASSIGN_TO_USER {
            get {
                return ResourceManager.GetString("LB_ASSIGN_TO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quản trị viên.
        /// </summary>
        public static string LB_ASSIGNED_USER {
            get {
                return ResourceManager.GetString("LB_ASSIGNED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string LB_AVATAR {
            get {
                return ResourceManager.GetString("LB_AVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string LB_CANCEL {
            get {
                return ResourceManager.GetString("LB_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục.
        /// </summary>
        public static string LB_CATEGORY_MANAGE {
            get {
                return ResourceManager.GetString("LB_CATEGORY_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string LB_CHANGE_PWD {
            get {
                return ResourceManager.GetString("LB_CHANGE_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra đường link truy cập.
        /// </summary>
        public static string LB_CHECK_VALID_LINK {
            get {
                return ResourceManager.GetString("LB_CHECK_VALID_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra lại quyền.
        /// </summary>
        public static string LB_CHECK_YOUR_PEMISSIONS {
            get {
                return ResourceManager.GetString("LB_CHECK_YOUR_PEMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file.
        /// </summary>
        public static string LB_CHOOSE_FILE {
            get {
                return ResourceManager.GetString("LB_CHOOSE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click xem chi tiết.
        /// </summary>
        public static string LB_CLICK_VIEW_DETAIL {
            get {
                return ResourceManager.GetString("LB_CLICK_VIEW_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string LB_CLOSE {
            get {
                return ResourceManager.GetString("LB_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string LB_CODE {
            get {
                return ResourceManager.GetString("LB_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài mã vạch.
        /// </summary>
        public static string LB_CODE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("LB_CODE_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu gọn.
        /// </summary>
        public static string LB_COLLAPSE {
            get {
                return ResourceManager.GetString("LB_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string LB_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("LB_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng trong kho sẽ được cập nhật lại theo số lượng kiểm kê. Bạn chắc chắn muốn thực hiện ?.
        /// </summary>
        public static string LB_CONFIRM_REFLECT_STOCK_TAKE {
            get {
                return ResourceManager.GetString("LB_CONFIRM_REFLECT_STOCK_TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu sẽ đặt về mặc định. Bạn có chắc chắn muốn làm lại mật khẩu ?.
        /// </summary>
        public static string LB_CONFIRM_RESET_PWD {
            get {
                return ResourceManager.GetString("LB_CONFIRM_RESET_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần kiểm kê.
        /// </summary>
        public static string LB_CONFIRM_STOCK_QTY {
            get {
                return ResourceManager.GetString("LB_CONFIRM_STOCK_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string LB_CONTENT {
            get {
                return ResourceManager.GetString("LB_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh bìa.
        /// </summary>
        public static string LB_COVER {
            get {
                return ResourceManager.GetString("LB_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh bìa.
        /// </summary>
        public static string LB_COVER_IMAGE {
            get {
                return ResourceManager.GetString("LB_COVER_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chức năng mới.
        /// </summary>
        public static string LB_CREATE_NEW_FUNCTION {
            get {
                return ResourceManager.GetString("LB_CREATE_NEW_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string LB_CREATED_BY {
            get {
                return ResourceManager.GetString("LB_CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string LB_CREATED_DATE {
            get {
                return ResourceManager.GetString("LB_CREATED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng hiện tại.
        /// </summary>
        public static string LB_CURRENT_QTY {
            get {
                return ResourceManager.GetString("LB_CURRENT_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string LB_DASHBOARD {
            get {
                return ResourceManager.GetString("LB_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giao diện thân thiện, đa chức năng và dễ sử dụng để quản lý dữ liệu..
        /// </summary>
        public static string LB_DASHBOARD_WELCOME_SLOGAN {
            get {
                return ResourceManager.GetString("LB_DASHBOARD_WELCOME_SLOGAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang sử dụng.
        /// </summary>
        public static string LB_DASHBOARD_WELCOME_TO {
            get {
                return ResourceManager.GetString("LB_DASHBOARD_WELCOME_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặc định.
        /// </summary>
        public static string LB_DEFAULT {
            get {
                return ResourceManager.GetString("LB_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian trễ.
        /// </summary>
        public static string LB_DELAYTIME {
            get {
                return ResourceManager.GetString("LB_DELAYTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string LB_DELETE {
            get {
                return ResourceManager.GetString("LB_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string LB_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("LB_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string LB_DESCRIPTION {
            get {
                return ResourceManager.GetString("LB_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị.
        /// </summary>
        public static string LB_DEVICE {
            get {
                return ResourceManager.GetString("LB_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id thiết bị.
        /// </summary>
        public static string LB_DEVICE_ID {
            get {
                return ResourceManager.GetString("LB_DEVICE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thiết bị.
        /// </summary>
        public static string LB_DEVICE_NAME {
            get {
                return ResourceManager.GetString("LB_DEVICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string LB_DISPLAY {
            get {
                return ResourceManager.GetString("LB_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string LB_DISPLAYING {
            get {
                return ResourceManager.GetString("LB_DISPLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị.
        /// </summary>
        public static string LB_DISPLAYNAME {
            get {
                return ResourceManager.GetString("LB_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã tồn tại. Vui lòng kiểm tra lại.
        /// </summary>
        public static string LB_DUPLICATE_DATA {
            get {
                return ResourceManager.GetString("LB_DUPLICATE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string LB_EDIT {
            get {
                return ResourceManager.GetString("LB_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bài viết.
        /// </summary>
        public static string LB_EDIT_POST {
            get {
                return ResourceManager.GetString("LB_EDIT_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LB_EMAIL {
            get {
                return ResourceManager.GetString("LB_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        public static string LB_ENUM_VALUE {
            get {
                return ResourceManager.GetString("LB_ENUM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi.
        /// </summary>
        public static string LB_ERROR_OCCURED {
            get {
                return ResourceManager.GetString("LB_ERROR_OCCURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sự kiện.
        /// </summary>
        public static string LB_EVENT_ACTIVITY {
            get {
                return ResourceManager.GetString("LB_EVENT_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ lọc.
        /// </summary>
        public static string LB_FILTER_ON_MAP {
            get {
                return ResourceManager.GetString("LB_FILTER_ON_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đầu.
        /// </summary>
        public static string LB_FIRST_PAGE {
            get {
                return ResourceManager.GetString("LB_FIRST_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string LB_FROM_DATE {
            get {
                return ResourceManager.GetString("LB_FROM_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chung.
        /// </summary>
        public static string LB_GENERAL {
            get {
                return ResourceManager.GetString("LB_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string LB_GOBACK {
            get {
                return ResourceManager.GetString("LB_GOBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho.
        /// </summary>
        public static string LB_GOODS_ISSUE {
            get {
                return ResourceManager.GetString("LB_GOODS_ISSUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho thành công !.
        /// </summary>
        public static string LB_GOODS_ISSUE_SUCCESS {
            get {
                return ResourceManager.GetString("LB_GOODS_ISSUE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho.
        /// </summary>
        public static string LB_GOODS_RECEIPT {
            get {
                return ResourceManager.GetString("LB_GOODS_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho thành công !.
        /// </summary>
        public static string LB_GOODS_RECEIPT_SUCCESS {
            get {
                return ResourceManager.GetString("LB_GOODS_RECEIPT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm kê thành công !.
        /// </summary>
        public static string LB_GOODS_REFLECT_STOCK_TAKE_SUCCESS {
            get {
                return ResourceManager.GetString("LB_GOODS_REFLECT_STOCK_TAKE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        public static string LB_GRANT_PERMISSION {
            get {
                return ResourceManager.GetString("LB_GRANT_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền cho nhóm.
        /// </summary>
        public static string LB_GRANT_PERMISSION_TO_ROLE {
            get {
                return ResourceManager.GetString("LB_GRANT_PERMISSION_TO_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string LB_GROUP {
            get {
                return ResourceManager.GetString("LB_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có quản trị viên.
        /// </summary>
        public static string LB_HAS_NO_ASSIGNED_USER {
            get {
                return ResourceManager.GetString("LB_HAS_NO_ASSIGNED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string LB_HAS_NO_DATA {
            get {
                return ResourceManager.GetString("LB_HAS_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình mặc định của máy quét.
        /// </summary>
        public static string LB_HT_DEFAULT_SETTING {
            get {
                return ResourceManager.GetString("LB_HT_DEFAULT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu tượng.
        /// </summary>
        public static string LB_ICON {
            get {
                return ResourceManager.GetString("LB_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string LB_IMAGE {
            get {
                return ResourceManager.GetString("LB_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string LB_INFORMATION {
            get {
                return ResourceManager.GetString("LB_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công.
        /// </summary>
        public static string LB_INSERT_SUCCESS {
            get {
                return ResourceManager.GetString("LB_INSERT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã khóa.
        /// </summary>
        public static string LB_IS_LOCKED {
            get {
                return ResourceManager.GetString("LB_IS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là chủ sở hữu.
        /// </summary>
        public static string LB_IS_OWNER {
            get {
                return ResourceManager.GetString("LB_IS_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string LB_ITEM_CODE {
            get {
                return ResourceManager.GetString("LB_ITEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string LB_ITEM_NAME {
            get {
                return ResourceManager.GetString("LB_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng còn lại trong kho.
        /// </summary>
        public static string LB_ITEM_REMAINS_IN_WAREHOUSE {
            get {
                return ResourceManager.GetString("LB_ITEM_REMAINS_IN_WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string LB_KEYWORD {
            get {
                return ResourceManager.GetString("LB_KEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục, mã danh mục,....
        /// </summary>
        public static string LB_KEYWORD_CAT_PLACEHOLDER {
            get {
                return ResourceManager.GetString("LB_KEYWORD_CAT_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm, tên sản phẩm.
        /// </summary>
        public static string LB_KEYWORD_ITEMNAME_ITEMCODE {
            get {
                return ResourceManager.GetString("LB_KEYWORD_ITEMNAME_ITEMCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa tìm kiếm....
        /// </summary>
        public static string LB_KEYWORD_SEARCH {
            get {
                return ResourceManager.GetString("LB_KEYWORD_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string LB_LANG_ENGLISH {
            get {
                return ResourceManager.GetString("LB_LANG_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string LB_LANG_VIETNAMESE {
            get {
                return ResourceManager.GetString("LB_LANG_VIETNAMESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string LB_LANGUAGE {
            get {
                return ResourceManager.GetString("LB_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cuối.
        /// </summary>
        public static string LB_LAST_PAGE {
            get {
                return ResourceManager.GetString("LB_LAST_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều hướng.
        /// </summary>
        public static string LB_LINK {
            get {
                return ResourceManager.GetString("LB_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string LB_LIST {
            get {
                return ResourceManager.GetString("LB_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải.
        /// </summary>
        public static string LB_LOADING {
            get {
                return ResourceManager.GetString("LB_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        public static string LB_LOCK {
            get {
                return ResourceManager.GetString("LB_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã khóa.
        /// </summary>
        public static string LB_LOCKED {
            get {
                return ResourceManager.GetString("LB_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string LB_LOGIN {
            get {
                return ResourceManager.GetString("LB_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string LB_LOGOUT {
            get {
                return ResourceManager.GetString("LB_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý các thành phần của slide.
        /// </summary>
        public static string LB_MANAGE_SLIDE_ITEM {
            get {
                return ResourceManager.GetString("LB_MANAGE_SLIDE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh dấu nổi bật.
        /// </summary>
        public static string LB_MARK_HIGHLIGHTS {
            get {
                return ResourceManager.GetString("LB_MARK_HIGHLIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho tối thiểu.
        /// </summary>
        public static string LB_MIN_INVENTORY {
            get {
                return ResourceManager.GetString("LB_MIN_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đa ngôn ngữ.
        /// </summary>
        public static string LB_MULTI_LANGUAGES {
            get {
                return ResourceManager.GetString("LB_MULTI_LANGUAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của tôi.
        /// </summary>
        public static string LB_MYPROFILE {
            get {
                return ResourceManager.GetString("LB_MYPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string LB_NAME {
            get {
                return ResourceManager.GetString("LB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string LB_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("LB_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang tiếp.
        /// </summary>
        public static string LB_NEXT_PAGE {
            get {
                return ResourceManager.GetString("LB_NEXT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string LB_NO {
            get {
                return ResourceManager.GetString("LB_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bản ghi nào.
        /// </summary>
        public static string LB_NO_RECORD {
            get {
                return ResourceManager.GetString("LB_NO_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý.
        /// </summary>
        public static string LB_NOTE {
            get {
                return ResourceManager.GetString("LB_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống sẽ lấy dữ liệu mặc định nếu dữ liệu đa ngôn ngữ không tồn tại.
        /// </summary>
        public static string LB_NOTE_MULTILANG_NULL {
            get {
                return ResourceManager.GetString("LB_NOTE_MULTILANG_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string LB_NOTIFICATION {
            get {
                return ResourceManager.GetString("LB_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng ký tự.
        /// </summary>
        public static string LB_NUMBER_OF_CHARACTERS {
            get {
                return ResourceManager.GetString("LB_NUMBER_OF_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to của.
        /// </summary>
        public static string LB_OF {
            get {
                return ResourceManager.GetString("LB_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string LB_OLD_PASSWORD {
            get {
                return ResourceManager.GetString("LB_OLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thực hiện.
        /// </summary>
        public static string LB_OPERATION_DATE {
            get {
                return ResourceManager.GetString("LB_OPERATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác thành công.
        /// </summary>
        public static string LB_OPERATION_SUCCESS {
            get {
                return ResourceManager.GetString("LB_OPERATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự hiển thị.
        /// </summary>
        public static string LB_ORDER_DISPLAY {
            get {
                return ResourceManager.GetString("LB_ORDER_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại cha.
        /// </summary>
        public static string LB_PARENT_CATEGORY {
            get {
                return ResourceManager.GetString("LB_PARENT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string LB_PASSWORD {
            get {
                return ResourceManager.GetString("LB_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được thay đổi về mặc định.
        /// </summary>
        public static string LB_PASSWORD_RESET_SUCCESS {
            get {
                return ResourceManager.GetString("LB_PASSWORD_RESET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string LB_PHONE {
            get {
                return ResourceManager.GetString("LB_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết nổi bật.
        /// </summary>
        public static string LB_POST_HIGHLIGHTS {
            get {
                return ResourceManager.GetString("LB_POST_HIGHLIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại bài viết.
        /// </summary>
        public static string LB_POST_TYPE {
            get {
                return ResourceManager.GetString("LB_POST_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đăng.
        /// </summary>
        public static string LB_POSTER {
            get {
                return ResourceManager.GetString("LB_POSTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang trước.
        /// </summary>
        public static string LB_PREVIOUS_PAGE {
            get {
                return ResourceManager.GetString("LB_PREVIOUS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm.
        /// </summary>
        public static string LB_PRODUCT_CATEGORY {
            get {
                return ResourceManager.GetString("LB_PRODUCT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý sản phẩm.
        /// </summary>
        public static string LB_PRODUCT_MANAGE {
            get {
                return ResourceManager.GetString("LB_PRODUCT_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string LB_PROFILE {
            get {
                return ResourceManager.GetString("LB_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các thuộc tính.
        /// </summary>
        public static string LB_PROPERTIES {
            get {
                return ResourceManager.GetString("LB_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        public static string LB_PROVIDER {
            get {
                return ResourceManager.GetString("LB_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhà cung cấp.
        /// </summary>
        public static string LB_PROVIDER_MANAGE {
            get {
                return ResourceManager.GetString("LB_PROVIDER_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp.
        /// </summary>
        public static string LB_PROVIDER_NAME {
            get {
                return ResourceManager.GetString("LB_PROVIDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string LB_QTY {
            get {
                return ResourceManager.GetString("LB_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản ghi.
        /// </summary>
        public static string LB_RECORD {
            get {
                return ResourceManager.GetString("LB_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản ghi.
        /// </summary>
        public static string LB_RECORDS {
            get {
                return ResourceManager.GetString("LB_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm kê.
        /// </summary>
        public static string LB_REFLECT_STOCK_TAKE {
            get {
                return ResourceManager.GetString("LB_REFLECT_STOCK_TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duy trì đăng nhập.
        /// </summary>
        public static string LB_REMEMBER_LOGIN {
            get {
                return ResourceManager.GetString("LB_REMEMBER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho tối thiểu.
        /// </summary>
        public static string LB_REORDER_POINT {
            get {
                return ResourceManager.GetString("LB_REORDER_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string LB_RESET {
            get {
                return ResourceManager.GetString("LB_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm lại mật khẩu.
        /// </summary>
        public static string LB_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("LB_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được thay đổi thành công.
        /// </summary>
        public static string LB_RESET_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("LB_RESET_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string LB_ROLE {
            get {
                return ResourceManager.GetString("LB_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc nhóm.
        /// </summary>
        public static string LB_ROLES_ASSIGNED {
            get {
                return ResourceManager.GetString("LB_ROLES_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string LB_SAVE {
            get {
                return ResourceManager.GetString("LB_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string LB_SEARCH {
            get {
                return ResourceManager.GetString("LB_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thành viên.
        /// </summary>
        public static string LB_SELECT_MEMBER {
            get {
                return ResourceManager.GetString("LB_SELECT_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại sản phẩm.
        /// </summary>
        public static string LB_SELECT_PRODUCT_CATEGORY {
            get {
                return ResourceManager.GetString("LB_SELECT_PRODUCT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhà cung cấp.
        /// </summary>
        public static string LB_SELECT_PROVIDER {
            get {
                return ResourceManager.GetString("LB_SELECT_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhóm.
        /// </summary>
        public static string LB_SELECT_ROLE {
            get {
                return ResourceManager.GetString("LB_SELECT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string LB_SETTINGS {
            get {
                return ResourceManager.GetString("LB_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần thiếu.
        /// </summary>
        public static string LB_SHORTAGE {
            get {
                return ResourceManager.GetString("LB_SHORTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string LB_STAFF {
            get {
                return ResourceManager.GetString("LB_STAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sao.
        /// </summary>
        public static string LB_STAR {
            get {
                return ResourceManager.GetString("LB_STAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí bắt đầu.
        /// </summary>
        public static string LB_START_POSITION {
            get {
                return ResourceManager.GetString("LB_START_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string LB_STATUS {
            get {
                return ResourceManager.GetString("LB_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập kho.
        /// </summary>
        public static string LB_STOCK_OUT {
            get {
                return ResourceManager.GetString("LB_STOCK_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng trong kho.
        /// </summary>
        public static string LB_STOCK_QTY {
            get {
                return ResourceManager.GetString("LB_STOCK_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng kiểm kê.
        /// </summary>
        public static string LB_STOCK_TAKE_QTY {
            get {
                return ResourceManager.GetString("LB_STOCK_TAKE_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian lưu lịch sử (tháng).
        /// </summary>
        public static string LB_STORAGE_HISTORY_PERIOD_TIME {
            get {
                return ResourceManager.GetString("LB_STORAGE_HISTORY_PERIOD_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian lưu giữ lịch sử thao tác của hệ thống (Sẽ xóa sau &apos;x&apos; tháng).
        /// </summary>
        public static string LB_STORAGE_HISTORY_PERIOD_TIME_DES {
            get {
                return ResourceManager.GetString("LB_STORAGE_HISTORY_PERIOD_TIME_DES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang bận, vui lòng thử lại sau hoặc liên hệ Admin để biết thêm chi tiết..
        /// </summary>
        public static string LB_SYSTEM_BUSY {
            get {
                return ResourceManager.GetString("LB_SYSTEM_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình hệ thống.
        /// </summary>
        public static string LB_SYTEM_SETTING {
            get {
                return ResourceManager.GetString("LB_SYTEM_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ &quot;Admin&quot; để biết thêm chi tiết.
        /// </summary>
        public static string LB_TELL_ADMIN_ABOUTIT {
            get {
                return ResourceManager.GetString("LB_TELL_ADMIN_ABOUTIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử mới nhất.
        /// </summary>
        public static string LB_THE_LATEST_HISTORY {
            get {
                return ResourceManager.GetString("LB_THE_LATEST_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string LB_TITLE {
            get {
                return ResourceManager.GetString("LB_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đến.
        /// </summary>
        public static string LB_TO {
            get {
                return ResourceManager.GetString("LB_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string LB_TO_DATE {
            get {
                return ResourceManager.GetString("LB_TO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử các cách sau.
        /// </summary>
        public static string LB_TRY_ONE_FOLLOWING {
            get {
                return ResourceManager.GetString("LB_TRY_ONE_FOLLOWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên, địa chỉ email, số điện thoại.
        /// </summary>
        public static string LB_TYPE_USER_SEARCH {
            get {
                return ResourceManager.GetString("LB_TYPE_USER_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string LB_UNIT {
            get {
                return ResourceManager.GetString("LB_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục đơn vị.
        /// </summary>
        public static string LB_UNIT_MASTER {
            get {
                return ResourceManager.GetString("LB_UNIT_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string LB_UNIT_SELECT {
            get {
                return ResourceManager.GetString("LB_UNIT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở khóa.
        /// </summary>
        public static string LB_UNLOCK {
            get {
                return ResourceManager.GetString("LB_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin.
        /// </summary>
        public static string LB_UPDATE_INFO {
            get {
                return ResourceManager.GetString("LB_UPDATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string LB_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("LB_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string LB_USERNAME {
            get {
                return ResourceManager.GetString("LB_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem danh sách quản trị viên.
        /// </summary>
        public static string LB_VIEW_ASSIGNED_USER {
            get {
                return ResourceManager.GetString("LB_VIEW_ASSIGNED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử hoạt động kho.
        /// </summary>
        public static string LB_WAREHOUSE_HISTORY {
            get {
                return ResourceManager.GetString("LB_WAREHOUSE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý kho.
        /// </summary>
        public static string LB_WAREHOUSE_MANAGE {
            get {
                return ResourceManager.GetString("LB_WAREHOUSE_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong kho.
        /// </summary>
        public static string LB_WAREHOUSE_STATUS {
            get {
                return ResourceManager.GetString("LB_WAREHOUSE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string LB_YES {
            get {
                return ResourceManager.GetString("LB_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề, nội dung,....
        /// </summary>
        public static string SEARCH_TITLE_CONTENT {
            get {
                return ResourceManager.GetString("SEARCH_TITLE_CONTENT", resourceCulture);
            }
        }
    }
}
